name: Publish To NPM

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          yarn

      - name: Run Tests
        run: |
          yarn test

      - name: Build
        run: |
          yarn build

      - name: Copy files
        run: |
          cp package.json dist/package.json
          cp README.md dist/README.md
          cp LICENSE dist/LICENSE

      - name: Setup Package Manager
        uses: actions/setup-node@master
        with:
          node-version: 14
          registry-url: "https://registry.npmjs.org/"

      - name: Publish to NPM
        run: |
          npm publish dist --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
